# Generated by Django 3.1.6 on 2021-02-21 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('region', models.TextField()),
                ('comuna', models.TextField()),
                ('direccion', models.TextField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('modelo', models.TextField(null=True)),
                ('descripcion', models.TextField(max_length=256)),
                ('stock', models.IntegerField(default=0)),
                ('precio_venta', models.IntegerField(default=0)),
                ('precio_compra', models.IntegerField(default=None, null=None)),
                ('img_producto', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('categoria', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='Tienda.categoria')),
                ('marca', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='Tienda.marca')),
            ],
        ),
    ]
